### ISSUE TITLE
Missing actual use-case

### ISSUE THREAD

**Issue by dakujem** [MrHash/TaskMachine#13]
I fail to understand what to use this library for.

Would it not be more legible and easier to code the following?

```php
    function pass(iterable $stages, mixed $passable = null): mixed
    {
        foreach ($stages as $stage) {
            $passable = $stage($passable);
        }
        return $passable;
    }
```

I can now construct the pipelines from the examples
```php
pass([
    function () {
        echo 'Hello World';
    },
    function () {
        echo 'Goodbye World';
    },
]);

pass([
    function (InputInterface $input) use ($container) {
        return new Input(
            text: $container->get(MyTranslator::class)->translate($input->get('text'))
        );
    },
    function (InputInterface $input) {
        echo $input->get('text');
    },
    function () {
        echo 'Goodbye World';
    },
], new Input(text: 'Hello World'));
```

I get the conditional branching can mix the dice, but then why not just place the `if` in PHP code directly?
```php
pass([
    function () {
        return (bool)random_int(0,1);
    },
    function (bool $result) use($container): TaskHandlerInterface {
        if($result){
            return new Finisher($myService)
        }
        return $container->get(MyCustomServiceInterface::class);
    },
    function (TaskHandlerInterface $handler) {
        return $handler->handle();
    },
]);
```

I understand these examples are oversimplified for legibility. Yet, I don't understand why I should not just use PHP.

I understand one may want to design pipelines on the fly, but this is trivial to do in plain PHP.  
Even if I wanted to implement service injection, it would be a couple of lines added to the `pass` method (provided we are using a library for that, like PHP-DI or Wire Genie).

> P.S. I came here searching for a state machine and this definitely is not one either.

**Comment by MrHash** [comment]
Underlying this little wrapper is a strong statemachine library with proper transitions and guards see https://github.com/MrHash/workflux. Sorry there isn't much documentation

**Comment by dakujem** [comment]
I see. That's what I have missed. The missing documentation/examples is an issue though.

**Comment by MrHash** [comment]
Understood, if you do end up using the lib and find it's worth making things clearer for others then PRs welcome. Have a look at the tests as well though, they should help.
